run:
	bit run everest

run-skip-watch:
	bit run everest --skip-watch

test:
	bit test everest

build:
	bit build everest

lint:
	bit lint everest --fix

format:
	bit format everest

test-ui:
	cd ui-tests && npx playwright test