name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch in the main branch
        run: |
          curl -XGET https://api.github.com/repos/percona/percona-everest-backend/actions/workflows \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.EVEREST_GITHUB_TOKEN }}' \
          curl -XPOST https://api.github.com/repos/percona/percona-everest-backend/actions/workflows/build.yml/dispatches \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.EVEREST_GITHUB_TOKEN }}' \
            --data '{"inputs": {}, "ref": "main"}' --fail-with-body
