name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.EVEREST_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/percona/percona-everest-backend/actions/workflows/62945358 --fail-with-body
      - name: Trigger dispatch in the main branch
        run: |
          curl -X POST -v https://api.github.com/repos/percona/percona-everest-backend/actions/workflows/62945358/dispatches \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            -H 'Authorization: token ${{ secrets.EVEREST_GITHUB_TOKEN }}' \
            --data '{"inputs": { "repo": "${{ github.repository }}" }, "ref": "PMM-7-test"}' --fail-with-body
