name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch in the main branch
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/percona/percona-everest-backend/actions/workflows/build.yml/dispatches \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${GITHUB_API_TOKEN}' \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --data '{"ref": "main"}' --fail-with-body
