name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch in the main branch
        with:
          workflow: E2E
          token: ${{ secrets.ROBOT_TOKEN }}
          repo: percona/percona-everest-backend

