name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch in the main branch
        env:
          EVEREST_GITHUB_TOKEN: ${{ secrets.EVEREST_GITHUB_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/percona/percona-everest-backend/actions/workflows/.github/workflows/build.yml/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${EVEREST_GITHUB_TOKEN}' \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --data '{"ref": "main"}' --fail-with-body
