name: Build and push dev-latest image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch in the main branch
        env:
          EVEREST_GITHUB_TOKEN: ${{ secrets.EVEREST_GITHUB_TOKEN }}
        run: |
          curl -XPOST https://api.github.com/repos/percona/percona-everest-backend/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H "Content-Type: application/json" \
            -u "${EVEREST_GITHUB_TOKEN}" \
            --data '{"event_type": "build_dev_latest"}' --fail-with-body
