---
name: CI
on:
  schedule:
    - cron: '0 12 * * 0'
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write
  repository-projects: read

env:
  NODE_OPTIONS: "—-max_old_space_size=4096"

jobs:
  cache_pnpm:
    name: Install and Cache PNPM
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-workspace.yaml'

    - name: Install dependencies
      run: make init

  CI_checks:
    runs-on: ubuntu-latest
    needs: cache_pnpm
    strategy:
      matrix:
        action: ['lint', 'test', 'build']
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-workspace.yaml'

    - name: lint
      if:  matrix.action == 'lint'
      run: |
        make init
        make lint

    - name: test
      if:  matrix.action == 'test'
      run: |
        make init
        make test

    - name: build
      if:  matrix.action == 'build'
      run: | 
        make init
        make build

  E2E:
    name: E2E Tests
    needs: cache_pnpm
    runs-on: ubuntu-20.04
    env:
      GOPRIVATE: github.com/percona,github.com/percona/percona-everest-backend,github.com/percona/percona-everest-cli,github.com/percona/everest-operator
    steps:
      - uses: actions/checkout@v3
        with:
          path: FE
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
          cache-dependency-path: FE/pnpm-workspace.yaml

      - name: Run Everest
        run: |
          make init
          pnpm --filter "@percona/everest" dev &

      - name: Checkout CLI repo
        uses: percona-platform/checkout@v3
        with:
          repository: percona/percona-everest-cli
          ref: 'main'
          path: CLI

      - name: Checkout backend repo
        uses: percona-platform/checkout@v3
        with:
          repository: percona/percona-everest-backend
          ref: 'main'
          path: BE

      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up Go release
        uses: percona-platform/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Set GO_VERSION environment variable
        run: |
          go version
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - name: Run Everest backend
        run: |
          cd BE
          make init
          make local-env-up
          touch everest-backend.log
          SECRETS_ROOT_KEY=$(openssl rand -base64 32) make run-debug &> everest-backend.log &

      - name: Archive backend log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: everest-backend.log
          path: ./percona-everest-backend/everest-backend.log

      - name: Create KIND cluster
        uses: helm/kind-action@v1.8.0

      - name: Wait for EVEREST BE to be available
        timeout-minutes: 15
        run: |
          while ! curl -sSf http://127.0.0.1:8080 > /dev/null; do
            echo "Waiting for EVEREST BE..."
            sleep 15
          done
          echo "EVEREST BE is available."

      - name: Run Provisioning
        run: |
          cd CLI
          go run cmd/everest/main.go install operators --backup.enable=false --everest.endpoint=http://127.0.0.1:8080 --monitoring.enable=false --name=minikube --operator.mongodb=true --operator.postgresql=true --operator.xtradb-cluster=true --skip-wizard --namespace test-everest

      - name: Run integration tests
        run: |
          cd FE/apps/everest
          pnpm --filter "@percona/everest" e2e

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: FE/apps/everest/.e2e/test-results/

      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: FE/apps/everest/.e2e/playwright-report/
