---
name: Lint/Format
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: ESLint & format
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run with Node 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Bit
        run: make install-bit

      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: bit config set user.token $BIT_TOKEN

      - name: Install dependencies
        run: make init

      - name: Run linter 
        run: make lint

      - name: Run formatter
        run: make format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: format files [--skip-ci]"
          file_pattern: ':(exclude)pnpm-lock.yaml'
