---
name: Lint/Format
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: ESLint & format
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run with Node 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Bit Version Manager 
        run: npm i -g @teambit/bvm

      - name: Install latest Bit version 
        run: bvm install

      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: bit config set user.token $BIT_TOKEN

      - name: Install dependencies
        run: bit install

      - name: Run linter 
        run: bit lint

      - name: Run formatter
        run: bit format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] chore: format files"
