---
name: Lint and Format
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: ESLint and Prettier
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: percona-platform/checkout@v2

      - name: Run with Node 16
        uses: percona-platform/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Bit Version Manager 
        run: npm i -g @teambit/bvm

      - name: Install latest Bit version 
        run: bvm install

      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: |
            bit config set user.token $BIT_TOKEN

      - name: Cache dependencies
        uses: percona-platform/cache@v2
        id: pnpm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: bit install

      - name: Run linter 
        run: bit lint
